# Generated by Django 5.0.6 on 2026-02-16 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_context', models.JSONField(blank=True, default=dict, help_text='Stores user preferences, brand info, past style choices, etc.')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(help_text='The text content of the message')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image_generation', 'Image Generation'), ('image_transformation', 'Image Transformation'), ('poster_design', 'Poster Design'), ('vision_board', 'Vision Board'), ('brand_artwork', 'Brand Artwork'), ('video_loop', 'Video Loop'), ('story_sequence', 'Story Sequence'), ('mixed', 'Mixed Content')], default='text', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('poster', 'Poster'), ('artwork', 'Artwork'), ('photo', 'Photo'), ('video_frame', 'Video Frame'), ('vision_board', 'Vision Board'), ('signage', 'Signage'), ('brand_asset', 'Brand Asset')], default='image', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(help_text='URL of the generated image (external or local media)', max_length=500)),
                ('prompt_used', models.TextField(blank=True, default='', help_text='The actual prompt used for generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='chat.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
